import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const GCMilan = localFont({
  src: [
    {
      path: "./fonts/GCMilan.ttf",
      style: "normal",
    },
  ],
  variable: "--font-gc-milan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mappetite AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${GCMilan.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
